### ISSUE TITLE
Amount to handle problematic values 

### ISSUE THREAD

**Issue by Berttwm** [AY1920S1-CS2103T-W12-3/main#132]
MAX.Integer
0
Negative

**Comment by joloong** [comment]
@dingyuchen mentioned that we should limit to 1billion = `1 000 000 000` since we do calculations with it. Exception should be thrown/displayed to user if input is greater than `Amount.MAX_VALUE`

Update UG/DG regarding this restriction.

**Comment by dingyuchen** [comment]
1billion limit should be enforced at Parsing stage -- need to move checking function out of constructor.
Throwing `OverflowException` if limit is exceeded during calculations might be a better approach, since regardless of construction limit, user can accrue enough transactions to reach Integer.MAX_VALUE.

**Comment by Berttwm** [comment]
Yes I will be enforcing this a parser
