### ISSUE TITLE
Better error message?

### ISSUE THREAD

**Issue by dingyuchen** [AY1920S1-CS2103T-W12-3/main#247]
>Wrong error thrown? (Amounts should only be in integer or double, and it should not be blank)
>split a/haidilao n/John Doe n/John Moe s/1 s/10000000000 $/1

Trace dataflow for rebalance. might not be bug

**Comment by Berttwm** [comment]
I think it's because your shares `s/1000000000000` throws Amount.MessageConstraints. I think Amounts should only be used for dollar valued variables because the checks and errors I have created is mainly for them. You can just create new error messages in the Messages class file to handle these issues.
